### ISSUE TITLE
phpseclib dependency

### ISSUE THREAD

**Issue by kronthto** [acodercat/php-jwk-to-pem#7]
Hi,

can you consider making it possible to install this package in projects phpseclib at v3 is already in use?

**Comment by acodercat** [comment]
Yes!

**Comment by Levivb** [comment]
cool! 😀

**Comment by kronthto** [comment]
Apparently there is https://github.com/phpseclib/phpseclib2_compat for that reason so nothing to be done here :)

**Comment by acodercat** [comment]
nice!

**Comment by Levivb** [comment]
you'd still need to allow v3 in `composer.json` (and add the compat dependency) to allow composer to resolve the updated dependency ;)

**Comment by kronthto** [comment]
The compat includes an "provides" that overrides that:

https://github.com/phpseclib/phpseclib2_compat/blob/55accea54bcdcd3ff02ca003c2750c1067a86002/composer.json#L19

**Comment by Levivb** [comment]
oh, that's pretty neat!

**Comment by acodercat** [comment]
I will update it this week.

**Comment by acodercat** [comment]
released.
