### ISSUE TITLE
Compatibility with phpseclib/phpseclib ^3

### ISSUE THREAD

**Issue by bzikarsky** [acodercat/php-jwk-to-pem#8]
Is it possible to add compatibility for `phpseclib/phpseclib` v3? Quite a few projects (e.g. `google/apiclient`) manage a `2||3` dependency.

Thank you.

**Comment by acodercat** [comment]
No problem, I will submit an update recently.

**Comment by acodercat** [comment]
released!

**Comment by bzikarsky** [comment]
Thanks :)
